# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'crowdping' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for crowdping

	#Pods from Google Firebase Cloud Messaging
	pod 'Firebase'
  	pod 'Firebase/Core'
  	pod 'Firebase/Messaging'

  target 'crowdpingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'crowdpingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
